# Generated by Django 3.2.7 on 2021-09-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='author_name',
            field=models.CharField(default='author', max_length=150, verbose_name='Ім’я автора'),
            preserve_default=False,
        ),
    ]
