# Generated by Django 3.2.7 on 2021-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_new_author_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Article',
        ),
    ]
